### PR TITLE
Add Support For Negative Enum Values

### PR DESCRIPTION
**Pull request by Halen84**
Currently, enums with a negative value will cause a integer overflow which isn't good because the result is not the real value of the enum.

### CODE REVIEW

**Comment by alexguirre** [comment]
There is no overflow happening. It is the same bits interpreted as unsigned vs signed integer. `4294967295 == -1` in 32-bit ints and `18446744073709551615 == -1` in 64-bit ints.

The issue is that, as far as I can tell, the enum parser data doesn't store whether it was originally signed or unsigned, so I just used unsigned everywhere. With this change, other enums that should probably be unsigned would have negative values, for example, enums with hash values like `eEventType`.

**Comment by Halen84** [comment]
By overflow I meant the negative would roll over to the max size of the data type. Enums with hash values, it doesn't matter if its signed or unsigned because it will still equal the same string, and signed can easily be converted to unsigned.

**Comment by alexguirre** [comment]
Yeah, I know. And the same can be done with unsigned to signed values.

Anyways, not opposed to showing the values as signed, as seems `-1`/`4294967295`/`18446744073709551615`, `-2`/`4294967294`, etc. occur more often than actual unsigned values.

But this change breaks parsing existing dumps. GTA5 dumps still work because the max 32-bit `4294967295` still fits in `long` (though it still wouldn't be displayed as `-1`), but RDR3's 64-bit `18446744073709551615` doesn't fit.
```
Unhandled exception: System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int64.Parse(String s)
   at DumpFormatter.Json.ParMemberConverter.ParMemberUnified.ToConcreteMember() in D:\sources\rage-parser-dumps\src\DumpFormatter\Json\ParMemberConverter.cs:line 102
   at DumpFormatter.Json.ParMemberConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\sources\rage-parser-dumps\src\DumpFormatter\Json\ParMemberConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
```

Can you update the JSON dumps too? Don't need to run the .asi again with every version, just some script that reads the dumps and converts GTA5's enum values to 32-bit signed ints and RDR3's values to 64-bit signed ints.

**Comment by Halen84** [comment]
Is that error coming from a RDR3 dump using unsigned values?

Also, should the script be included in this repository?

**Comment by alexguirre** [comment]
> Is that error coming from a RDR3 dump using unsigned values?

Yeah, from the existing RDR3 dumps in the repo. I assume due to values like `18446744073709551615` which don't fit in `long`.

> Also, should the script be included in this repository?

Nah, this should be a one time thing, so it doesn't need to be in the repo.

**Comment by Halen84** [comment]
I think that should be good. Let me know if my script missed any.

**Comment by alexguirre** [comment]
GTA5 is missing the enum `0x92A659FE`. This is the diff between your updated dump and the dump generated by the .asi with the signed int changes in the latest version. RDR3 looks fine.
```diff
diff --git "a/.\\b2824.json" "b/.\\b2845.json"
index 222f49c..5c10b77 100644
--- "a/.\\b2824.json"
+++ "b/.\\b2845.json"
@@ -1,7 +1,7 @@
 
 {
 	"game": "gta5",
-	"build": 2824,
+	"build": 2845,
 	"structs": [
 	],
 	"enums": [
@@ -7355,23 +7355,23 @@
 			"values": [
 				{
 					"name": "0xD6811AC4",
-					"value": 4000413475
+					"value": -294553821
 				},
 				{
 					"name": "0xE7517F96",
-					"value": 2423432979
+					"value": -1871534317
 				},
 				{
 					"name": "0x0DD48139",
-					"value": 3626484699
+					"value": -668482597
 				},
 				{
 					"name": "0xC6D398AA",
-					"value": 4294436772
+					"value": -530524
 				},
 				{
 					"name": "0xD91DA8BF",
-					"value": 3179812827
+					"value": -1115154469
 				},
 				{
 					"name": "0x0DB3BE88",
@@ -7395,7 +7395,7 @@
 				},
 				{
 					"name": "0xB09F25FD",
-					"value": 2497303949
+					"value": -1797663347
 				},
 				{
 					"name": "0xB2141C33",
@@ -7407,11 +7407,11 @@
 				},
 				{
 					"name": "0x548A8BBA",
-					"value": 2439938700
+					"value": -1855028596
 				},
 				{
 					"name": "0x156C29B2",
-					"value": 3518960071
+					"value": -776007225
 				},
 				{
 					"name": "0x508B75C7",
@@ -7427,19 +7427,19 @@
 				},
 				{
 					"name": "0x6A718AF7",
-					"value": 4211833313
+					"value": -83133983
 				},
 				{
 					"name": "0x3A5EDC73",
-					"value": 3133206795
+					"value": -1161760501
 				},
 				{
 					"name": "0x4F20F21B",
-					"value": 3661668572
+					"value": -633298724
 				},
 				{
 					"name": "0x7472C20E",
-					"value": 3532676775
+					"value": -762290521
 				},
 				{
 					"name": "0xCD8E39C3",
@@ -24001,4 +24001,4 @@
 			]
 		}
 	]
-}
+}
\ No newline at end of file
```

**Comment by Halen84** [comment]
Not sure what's going on there? b2845 isn't in this repo.

**Comment by alexguirre** [comment]
b2845 doesn't matter, there are no changes regarding enums in this version. The `0x92A659FE` enum still has unsigned values in all versions. `4000413475` should be `-294553821`, etc.

**Comment by alexguirre** [comment]
And this is interesting, in RDR3
```jsonc
"enumName": "0xCF62AB23",
"initValue": 18446744072241044870
// now
"initValue": -1468506746
```
but in the enum value
```jsonc
"name": "0xCF62AB23",
"flags": "ENUM_STATIC",
"values": [
	{
		"name": "0xF645035F",
		"value": 2826460550
	},
```
Seems, with 32-bit enums, the `initValue` is sign-extended when converted to 64-bit, but the value in the enum entry isn't.
```
18446744072241044870      == 0xFFFFFFFFA8785D86
-1468506746 == 2826460550 == 0x00000000A8785D86
```
Anyways, don't need to worry about this, it was already an issue before. In any case, just something that the formatters should take into account if it actually causes any issues. The JSON is fine.

**Comment by Halen84** [comment]
Yea that was my bad. Was an issue with how I was checking for unsigned values.

**Comment by Halen84** [comment]
Also, what about initValue 4278190080 being converted to -16777216, when its type is UINT?

**Comment by alexguirre** [comment]
> Also, what about initValue 4278190080 being converted to -16777216, when its type is UINT?

That leave it as 4278190080. The game stores those init values as doubles so 4278190080 is correct.

**Comment by Halen84** [comment]
Should be fixed now

**Comment by alexguirre** [comment]
Perfect, thank you!

**Pull request merged**
